### ISSUE TITLE
gal 2.3.0 not compatible with gal_linux

### ISSUE THREAD

**Issue by lijianqiang12** [freshtechtips/gal-linux#1]
pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.
  Future<void> putImageBytes(Uint8List bytes, {String? album}) =>

pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
  Future<void> putImageBytes(Uint8List bytes,

**Comment by EchoEllet** [comment]
> pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.
>   Future<void> putImageBytes(Uint8List bytes, {String? album}) =>
> 
> pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
>   Future<void> putImageBytes(Uint8List bytes,

Hi! Thanks for letting me know, I will update it today

**Comment by EchoEllet** [comment]
> pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'. Future putImageBytes(Uint8List bytes, {String? album}) =>
> 
> pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes'). Future putImageBytes(Uint8List bytes,

`gal_linux` has been updated now, you can test the new version now

**Comment by lijianqiang12** [comment]
Thank you so much!

**Comment by EchoEllet** [comment]
> Thank you so much!

You're welcome
